### ISSUE TITLE
npm run build - Compiled with warnings.

### ISSUE THREAD

**Issue by CloudHoang** [danxfisher/MeetEasier#18]
Hi danxfisher,
I really interesting on your project and I try build one for my company.
But I got this while complied it as the picture below!
![image](https://user-images.githubusercontent.com/36913879/36775207-b49ac556-1c93-11e8-8e39-a468be7f0cc9.png)
Sorry I not good at coder so I cannot fix it.
Can you help me? 
Thanks so much!

**Comment by danxfisher** [comment]
The warnings are fine.  I will fix them in the future but they should have no impact on performance.
