### ISSUE TITLE
Meeting Title not displaying

### ISSUE THREAD

**Issue by 9uan9** [danxfisher/MeetEasier#21]
I think I have everything set up correctly as everything is working great.  Except that the title of the meeting does not display.  Instead it displays the meeting organizers name.  The issue is the same under Upcoming.  Where can I edit what elements are displayed?  Thanks

**Comment by 9uan9** [comment]
I noticed that it was displaying correctly for 1 of my rooms.  Upon comparing that to my other 6 rooms, I changed the names of the rooms to be 2 words instead of 3 words.  That didnt work.  I think because Identity was still the original even though display name was now 2 words.  So I deleted the rooms and recreated them.  That seems to have done the trick.  So "Main Conference Room" didnt work.  But "Main Conference" did work and displayed the subject rather than the organizer.

**Comment by Yasvah** [comment]
If the option on room is "Accept or decline booking resquete automatically" by default the subject is replaced by the meeting organizer name in room mailbox. (the meeting subject can be confidantiel)
![image](https://user-images.githubusercontent.com/6206139/41978148-7ca5e00e-7a21-11e8-9438-ee3013559c49.png)
But in the meeting organizer's calendar subject isn't replaced.
You can change this behaviour on Powershell.

**Comment by danxfisher** [comment]
Closing since this is unrelated to the application and just standard behavior from Exchange.
