### ISSUE TITLE
Issue with the credentials you have supplied

### ISSUE THREAD

**Issue by Collie147** [danxfisher/MeetEasier#58]
I can't seem to get it to work, I keep getting the following "Oops, there seems to be an issue with the credentials you have supplied.  Make sure you typed them correctly and that you have access to Exchange Roomlists".  I've tested it out with EWSEditor (https://github.com/dseph/EwsEditor ) and it all works fine.  I've even written some .net scripts to test and I can pull down the rooms that way too.  Is there any way to troubleshoot or any logging information outputted somewhere?

Thanks

**Comment by linkinlxm** [comment]
i have the same problem

**Comment by Collie147** [comment]
I managed to get it working. I had to use NTLM and set it to ignore certificate errors, using https://github.com/gautamsi/ews-javascript-api-auth
