### ISSUE TITLE
Book Now button

### ISSUE THREAD

**Issue by Collie147** [danxfisher/MeetEasier#59]
Awesome work by the way.  How easy/hard/complicated would it be to incorporate a book now button on the single-room screen for impromptu meetings.  I'm a novice with JS and totally new to node, but I'm giving it a go nonetheless.

What I'm trying is :

1. to check is if the room is free display the button to book now.  
2. If its busy and there is no concurrent meeting display another button to extend the booking.  

for both of those the buttons should be relatively the same
  a. check how long the room is free for (if 2 then check after the current booking) and display blocks of 15 minutes up to 2 hours.
  b. if one of the buttons is clicked book the room for that block of time selected.

**Comment by Gajack33** [comment]
@Collie147, Thanks for your update, very usefull.

Do you know if it's possible to add a button "Book Ended" to press when your meeting is over before before the end time ? I searched a little and i don't find any parameters to edit a meeting time ...

Do you already looked for it and found something?

**Comment by Eisbaeeer** [comment]
Both request will be fine and genius.

**Comment by Collie147** [comment]
I've forked my own version and added buttons and functions.  I haven't built it from the github files though I intend on doing so at a later date.

https://github.com/Collie147/MeetEasier
