### ISSUE TITLE
Roomlist requirement?

### ISSUE THREAD

**Issue by oskari** [danxfisher/MeetEasier#6]
Could this made to work without rooms being organized to room lists? As in, why is there such a requirement? I'm not familiar with the O365 Api but for my use I would just be fine with it fetching all rooms and having a black/whitelist feature for showing / hiding them.

**Comment by am-jo-zt** [comment]
Room lists do make sense if you have offices at different locations.

From what I have seen, it already is possible to blacklist meeting rooms. See `ui-react/src/config/flightboard.config.js`. However, I'd appreciate configuration at a more central place (in project root) and the rooms should be filtered by the server, not by the client.

**Comment by danxfisher** [comment]
Late to the party, but #26 has moved the blacklist to the backend.  Room lists are also the easiest way to pull all meeting rooms without manually specifying them in some other configuration file.  This may be something to look at in the future but won't be implemented currently.
