### ISSUE TITLE
No Data to display

### ISSUE THREAD

**Issue by zkenstein** [danxfisher/MeetEasier#62]
Hi, After successful install in page browser not showing rooms list, only spinning with in console log got: :`8080/api/rooms net::ERR_EMPTY_RESPONSE` anyone faced this issue?

Thanks,

**Comment by zkenstein** [comment]
Fixed.

**Comment by Guile17** [comment]
Hey @zkenstein, could you share what did you do to fix this issue? Tx

**Comment by zkenstein** [comment]
Hi @Guile17 ,

You need to add existing rooms to the room list, I tried from GUI but not worked, on my case, what I did is connect the mailbox to Powershell and than run the following command to add existing rooms to the room list

`Add-DistributionGroupMember <RoomListName> -Member <RoomMailbox>
`

Hope this help
