### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by MaxReck** [danxfisher/MeetEasier#77]
Since this uses Basic Authentication, the tool is no longer working

**Comment by canoas** [comment]
After October 1 2022 Exchange no longer supports basic auth
[https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#:~:text=In%20September%202021,2021%20Update](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#:~:text=In%20September%202021,2021%20Update)

**Comment by jordanoceros** [comment]
This sucks so much you can postpone the basic authentication until January as 365 admin all the other raspberry pi options are subscription based garbage on top of the exchange mailbox paid service. I'm trying some different scripts that might be able to use/save modern auth to this but idk. If we can not make this work does anyone have any better solutions?

**Comment by olsonnn** [comment]
So sad! i hope somebody can fix it!

**Comment by olsonnn** [comment]
good news here!!!!
https://github.com/probits-as/MeetEasier/commit/72c9bdbbebaed5a54a56a8b9f92d8d7ffbdb9193#commitcomment-86755485

got it working again!

**Comment by MaxReck** [comment]
> good news here!!!!
> https://github.com/probits-as/MeetEasier/commit/72c9bdbbebaed5a54a56a8b9f92d8d7ffbdb9193#commitcomment-86755485
> 
> got it working again!
> 

Just to be sure this implementation uses another way of authenticating like OAuth?

**Comment by olsonnn** [comment]
> Just to be sure this implementation uses another way of authenticating like OAuth?

Looks like you missed the step by step install on that page (scroll)

**Comment by fkmeland** [comment]
> Just to be sure this implementation uses another way of authenticating like OAuth?

Yes, this uses the Microsoft Graph API instead of the deprecated EWS API, and authenticates with OAuth.

I have updated the README in my repository with a better guide (hopefully) on how to register a application in azure ad to get the required credentials to use with the application.

https://github.com/probits-as/MeetEasier

**Comment by kaktuseek** [comment]
@fkmeland Many thanks!! The app is working again. Just a little thing - in your .env.template, you swapped the OAUTH_AUTHORITY and OAUTH_CLIENT_SECRET.

**Comment by fkmeland** [comment]
> @fkmeland Many thanks!! The app is working again. Just a little thing - in your .env.template, you swapped the OAUTH_AUTHORITY and OAUTH_CLIENT_SECRET.

Glad you got it working again, and thanks for letting me know about the error in the docs, they have been corrected 😊
